// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: cart.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceClient interface {
	GetCardDetailByIDs(ctx context.Context, in *GetCardDetailByIDsRequest, opts ...grpc.CallOption) (*GetCardDetailByIDsResponse, error)
	UpdateCartByIDs(ctx context.Context, in *UpdateCartByIDsRequest, opts ...grpc.CallOption) (*UpdateCartByIDsResponse, error)
}

type cartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartServiceClient(cc grpc.ClientConnInterface) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) GetCardDetailByIDs(ctx context.Context, in *GetCardDetailByIDsRequest, opts ...grpc.CallOption) (*GetCardDetailByIDsResponse, error) {
	out := new(GetCardDetailByIDsResponse)
	err := c.cc.Invoke(ctx, "/proto.CartService/GetCardDetailByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) UpdateCartByIDs(ctx context.Context, in *UpdateCartByIDsRequest, opts ...grpc.CallOption) (*UpdateCartByIDsResponse, error) {
	out := new(UpdateCartByIDsResponse)
	err := c.cc.Invoke(ctx, "/proto.CartService/UpdateCartByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
// All implementations must embed UnimplementedCartServiceServer
// for forward compatibility
type CartServiceServer interface {
	GetCardDetailByIDs(context.Context, *GetCardDetailByIDsRequest) (*GetCardDetailByIDsResponse, error)
	UpdateCartByIDs(context.Context, *UpdateCartByIDsRequest) (*UpdateCartByIDsResponse, error)
	mustEmbedUnimplementedCartServiceServer()
}

// UnimplementedCartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
}

func (UnimplementedCartServiceServer) GetCardDetailByIDs(context.Context, *GetCardDetailByIDsRequest) (*GetCardDetailByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardDetailByIDs not implemented")
}
func (UnimplementedCartServiceServer) UpdateCartByIDs(context.Context, *UpdateCartByIDsRequest) (*UpdateCartByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartByIDs not implemented")
}
func (UnimplementedCartServiceServer) mustEmbedUnimplementedCartServiceServer() {}

// UnsafeCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceServer will
// result in compilation errors.
type UnsafeCartServiceServer interface {
	mustEmbedUnimplementedCartServiceServer()
}

func RegisterCartServiceServer(s grpc.ServiceRegistrar, srv CartServiceServer) {
	s.RegisterService(&CartService_ServiceDesc, srv)
}

func _CartService_GetCardDetailByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardDetailByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetCardDetailByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/GetCardDetailByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetCardDetailByIDs(ctx, req.(*GetCardDetailByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_UpdateCartByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).UpdateCartByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/UpdateCartByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).UpdateCartByIDs(ctx, req.(*UpdateCartByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartService_ServiceDesc is the grpc.ServiceDesc for CartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardDetailByIDs",
			Handler:    _CartService_GetCardDetailByIDs_Handler,
		},
		{
			MethodName: "UpdateCartByIDs",
			Handler:    _CartService_UpdateCartByIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
